### ISSUE TITLE
tracedSVG support

### ISSUE THREAD

**Issue by baobabKoodaa** [d4rekanguok/gatsby-remark-custom-image-component#2]
Hi, would it be difficult to modify this so that tracedSVG parameter could be passed to plugin sharp? I think it's not possible to pass this parameter in JS config file. In GraphQL the request looks like this:

```
fixed() {
  src
  srcSet
  tracedSVG
}
```

**Comment by d4rekanguok** [comment]
@baobabKoodaa sorry I completely missed this issue — I would love to support sharp 100%, so it's good to do this. I'm short on time recently though so I can't say when it will be implemented!

BTW, if you're starting a new project from scratch, [gatsby-mdx](https://github.com/ChristopherBiscardi/gatsby-mdx) is a much more interesting way to do custom elements in markdown. I'm looking for a way to make it easier to intergrate into existing blog.

**Comment by baobabKoodaa** [comment]
Yeah no worries. I'm using `gatsby-remark-rehype-images` for now :)
