### ISSUE TITLE
Plugin not adding image sharp attributes to component

### ISSUE THREAD

**Issue by imchetanyadav** [d4rekanguok/gatsby-remark-custom-image-component#3]
Component is detected and its image thumbnails are also generated but for some reason image sharp attributes are not passed to component.

Here's a example repo based on gatsby-starter-blog
<https://github.com/imchetanyadav/gatsby-remark-custom-image-component-test>

**Comment by megant** [comment]
Only src is passed to ImageWrapper component, nothing else.

**Comment by imchetanyadav** [comment]
But it should also pass srcSet attributes for fluid so that I can achieve responsive image functionality. Even custom component example in readme show src and srcSet props passed to ImageWrapper (see below line from readme).
```
const ImageWrapper =  ({ src, srcSet }) => <img src={src} srcSet={srcSet} />
```

**Comment by d4rekanguok** [comment]
Hi @imchetanyadav, thank you for trying out this package & apologize for the late response -- for some reasons I receive email notification on every comment replies where else but _not for the issues in my own damn repos_! 

It looks like I wasn't properly handling a `undefined` property, which leads to weird behavior (god, I'm in dire need of tests). I've published a new version & thing seems to work properly in your [test repo](https://github.com/imchetanyadav/gatsby-remark-custom-image-component-test). If you can, please do a `@latest` install and see if that fixes the issue.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/3383539/58745668-7d110280-848e-11e9-9623-a27afeb70e0b.png">

### Small note
I have a few plans for this repo (handle all sharps properties, traceSVG, webp, multiple images) but haven't got a chance to implement them yet. In the mean time, if this doesn't do what you need, here are some alternatives:

- [MDX](https://github.com/ChristopherBiscardi/gatsby-mdx)
- [gatsby-remark-rehype-images](https://github.com/oorestisime/gatsby-remark-rehype-images), which has strikingly similar API & usage to this package but might have better support for traceSVG

Thank you again for trying this out & please watch the package if you're interested in its update!!

**Comment by imchetanyadav** [comment]
Yup, seems to be working fine now. Thanks for help. 
I will close the issue.
